spring.application.name=app_notifications_service
server.port=8081

# Health
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# RabbitMQ connection
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.virtual-host=/

# RabbitMQ producer retry
spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.max-attempts=3
spring.rabbitmq.template.retry.initial-interval=1000ms
spring.rabbitmq.template.retry.max-interval=10000ms
spring.rabbitmq.template.retry.multiplier=2.0

# Messaging topology
messaging.exchange.user=userExchange
messaging.exchange.dlx=user.dlx
messaging.queue.userCreated=userCreatedQueue
messaging.queue.userUpdated=userUpdatedQueue
messaging.queue.userDeleted=userDeletedQueue
messaging.queue.userCreated.dlq=userCreatedQueue.dlq
messaging.queue.userUpdated.dlq=userUpdatedQueue.dlq
messaging.queue.userDeleted.dlq=userDeletedQueue.dlq
messaging.routing.key.userCreated=user.created
messaging.routing.key.userUpdated=user.updated
messaging.routing.key.userDeleted=user.deleted

# Email SMTP
spring.mail.host=${GMAIL_HOST}
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true